function thdot_plus = jump(x)
global m m_H l r L1 L2 phi_init
phi = phi_init;
twoa = x(end,1)-x(end,3);
q_plus = [L1^2*m+L2^2*m+L1^2*m_H+2*m*r^2+m_H*r^2+2*L1*m*r*cos(phi+x(end,3))+2*L2*m*r*cos(phi+x(end,3))+2*L1*m_H*r*cos(phi+x(end,3))-(l*m*r*cos(phi+x(end,1)))/2-...
    (L1*l*m*cos(twoa))/2+L1*m*phi*r*sin(phi+x(end,3))+L2*m*phi*r*sin(phi+x(end,3))+L1*m_H*phi*r*sin(phi+x(end,3))+L1*m*r*x(end,3)*sin(phi+x(end,3))+...
    L2*m*r*x(end,3)*sin(phi+x(end,3))+L1*m_H*r*x(end,3)*sin(phi+x(end,3)),-(l*m*(2*r*cos(phi+x(end,1))-l+2*L1*cos(twoa)+2*phi*r*sin(phi+x(end,1))+2*r*x(end,3)*sin(phi+x(end,1))))/4;
    -(l*m*(r*cos(phi+x(end,1))+L1*cos(twoa)))/2,(l^2*m)/4];

q_minus = [2*m*r^2+m_H*r^2+L1^2*m_H*cos(twoa)-(L2*l*m)/2+L1*m*r*cos(phi+x(end,1))+L1*m*r*cos(phi+x(end,3))+L2*m*r*cos(phi+x(end,1))+L2*m*r*cos(phi+x(end,3))+...
    L1*m_H*r*cos(phi+x(end,1))+L1*m_H*r*cos(phi+x(end,3))+2*L1*L2*m*cos(twoa)-(l*m*r*cos(phi+x(end,1)))/2+L1*m*phi*r*sin(phi+x(end,1))+L2*m*phi*r*sin(phi+x(end,1))+...
    L1*m_H*phi*r*sin(phi+x(end,1))+L1*m*r*x(end,3)*sin(phi+x(end,1))+L2*m*r*x(end,3)*sin(phi+x(end,1))+L1*m_H*r*x(end,3)*sin(phi+x(end,1)),-(l*m*(L2+r*cos(phi+x(end,3))+...
    phi*r*sin(phi+x(end,3))+r*x(end,3)*sin(phi+x(end,3))))/2;-(l*m*(L2+r*cos(phi+x(end,1))))/2,0];
thdot_plus = q_plus\q_minus*[x(end,2); x(end,4)];
end
